apiVersion: apps/v1
kind: Deployment
metadata:
  name: zackweb
  labels:
    app: zackweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zackweb
  template:
    metadata:
      labels:
        app: zackweb
    spec:
      containers:
      - name: zackweb
        image: zackz001/gitops-jekyll:latest
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: zackweb-service
spec:
  selector:
    app: zackweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # 
