name: "zack gitops workflow for iac"
on: 
  push: 
    branches:
      - main
      - stage
    paths:             # any change in folder "terraform" 
      - terraform/**   # for both stage and main, will trigger workflow
  
  pull_request:        # no one can commit to main except approvel needed from main branch owner
    branches:          # raise pull_request when merge from stage to main
      - main           # will trigger workflow
    paths:          
      - terraform/**

env:                   # cred for AWS access, terrform is looking for      
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  # also can be stored in github var
  AWS_DEFAULT_REGION: ap-southeast-2
  #EKS_CLUSTER: zack-gitops-eks-prod

jobs: 
  terraform:   # create a ubuntu container, cd to terraform dir, checkout source code
    name: "apply iaac code change"
    runs-on: ubuntu-latest    # from github runners containers 
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    
    steps:

      - uses: actions/checkout@v3

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Debug AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"

      - name: setup terraform on runners
        uses: hashicorp/setup-terraform@v3
        #with:
         # terraform_version: "1.1.7"

      - name: terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: terraform fmt
        id: fmt
        run: terraform fmt -check  # will fail the workfolw if fmt incorrect, until return "0" to continue

      - name: terraform validate
        id: validate
        run: terraform validate  

      - name: terraform plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: terraform plan
        if: steps.plan.outcome == 'failure'
        run: exit 1 # if something goes wrong in the plan, fail the workflow